const Product = require("../models/Product");

function senderProduct() {
    const data = [
        {
            "title" : "Áo thun cây xương rồng",
            "slug": "Ao-thun-cay-xuong-rong",
            "price" : 200000,
            "description" : "Áo được in họa tiết tinh xảo",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 10,
            "published": true,
        }, 
        {
            "title" : "Áo thun trắng",
            "slug": "Ao-thun-trang",
            "price" : 100000,
            "description" : "Áo thung bằng coton",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 50,
            "published": false,
        }, 
        {
            "title" : "Quần kaki hồng",
            "slug": "Quan-kaki-hong",
            "price" : 2000000,
            "description" : "Hường sang chảnh",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 13,
            "published": true,
        }, 
        {
            "title" : "Áo sơ mi xanh dương",
            "slug": "Ao-so-mi-xanh-duong",
            "price" : 110000,
            "description" : "",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 50,
            "published": false,
        }, 
        {
            "title" : "Áo khoác màu nâu",
            "slug": " Ao-khoac-mau-nau",
            "price" : 2200000,
            "description" : "Một chiếc áo kiểu tây",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 100,
            "published": true,
        }, 
        {
            "title" : "Đồng hô đen",
            "slug": "DJong-ho-djen",
            "price" : 17000000,
            "description" : "Màu đen tạo cảm giác lịch lãm",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 65,
            "published": true,
        }, 
        {
            "title" : "Thắt lưng LV",
            "slug": "That-lung-LV",
            "price" : 320000,
            "description" : "Hiệu luôn vui tươi",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 10,
            "published": true,
        }, 
        {
            "title" : "Giày hiệu",
            "slug": "Giay-hieu",
            "price" : 180000,
            "description" : "Không phải fake",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 9,
            "published": true,
        }, 
        {
            "title" : "Quần Jean",
            "slug": "Quan-Jean",
            "price" :  699999,
            "description" : "Quần bò",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 10,
            "published": true,
        }, 
        {
            "title" : "Váy ngắn",
            "slug": "Vay-ngan",
            "price" : 50000,
            "description" : "Váy không dài",
            "views": 0,
            "sku": "sku",
            "discount": 0,
            "quantity": 10,
            "published": true,
        }, 
    ];
    return Product.insertMany(data)
}

module.exports = senderProduct